[package]
name = "spell-tower-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
phf = { version = "0.11.2", features = ["macros"] }
rusqlite = { version = "0.32.0", features = ["array", "bundled"] }
